### ISSUE TITLE
Issues with some of the warning visualisations

### ISSUE THREAD

**Issue by AnttiRumpunen** [smartmet-jm/weather-app#13]
Flash flood
- [x] warning discontinuation message is faulty - is generated as watch

Aerodrome Warnings
- [x] all good

Severe Weather Alert
- [x] land ok

Hurricane
- [x] land ok
- [x] warning discontinuation message is faulty - is generated as advisory

Tsunami
- [x] land ok

Tropical Storm
- [x] land ok

Thunderstorm
- [x] land ok

Storm Surge
- [x] land ok

Wind
- [x] land visualisation ok
- [x] land warning Severe and Extreme get into same category (warning) - this is ok

Rainfall
- [x] land ok

Landslide
- [x] land ok

Flood
- [x] land ok

Visibility
- [x] rain moderate and extreme has same texts
- [x] haze severe and extreme has same texts
- [x] fog severe and extreme has same texts
- [x] rain + fog extreme visualised ok
- [x] fog severe, both hazes are not visualised (eventually all are vis ok - see #36)

High Surf
- [x] land ok

Temperature
- [x] land ok

High Humidity
- [x] land ok

Bush Fire
- [x] extreme and severe are in the same category (warning) this is ok

Drought
- [x] land ok

Seasonal Temperature
- [x] shown as temperature outlook

Seasonal Rainfall
- [x] shown as rainfall outlook
- [x] #36 issue if both are active

Marine Severe Weather
- [x] sea ok

Thunderstorm
- [x] sea ok

Tropical Storm
- [x] sea ok

Strong wind and large waves
- [x] 20-25kt and 25-34kt are orange advisories => in same category
- [x] #36 issue with advisories

Rainfall
- [x] sea ok

Hurricane
- [x] warning discontinuation message is faulty - is generated as watch

Large wave warning for small craft
- [x] sea ok

**Comment by evnurm-cgi** [comment]
I tested the currently installed icons in the application - here's the result:

![warning-symbols-1](https://github.com/smartmet-jm/weather-app/assets/107606457/8142234e-1791-479c-ade0-1d2d88f4339d)
![warning-symbols-2](https://github.com/smartmet-jm/weather-app/assets/107606457/c6c39852-60f9-4aa7-8296-08a30040d07d)
![warning-symbols-3](https://github.com/smartmet-jm/weather-app/assets/107606457/bb75b1b9-eb4b-485e-a76d-3564a5f99aae)
![warning-symbols-4](https://github.com/smartmet-jm/weather-app/assets/107606457/30166264-ee70-425f-a8c0-3983f393e19f)

**Comment by AnttiRumpunen** [comment]
Which warnings need more specific investigation:
- [ ] Visibility (shows 7, but should be 6 pcs)
- [ ] Bush fire warning (shows 2, maybe severe + extreme)
- [ ] Tropical Storm Advisory Discontinuation (shows 2)
- [ ] Tropical Storm Warning Discontinuation (shows 2)
- [ ] Hurricane Warning (shows 2)
- [ ] Tropical Storm Advisory (shows 2)
- [ ] Tropical Storm Watch (shows 2)
- [ ] Strong Wind Warning (shows 2, 118kmh and 67kmh)
- [ ] Hurricane Advisory Discontinuation (shows 4)
- [ ] Hurricane Watch Discontinuation (shows 2)
- [ ] Hurricane Advisory (shows 2)
- [ ] Hurricane Watch (shows 2)
- [ ] Tropical Storm Watch Discontinuation (shows 2)
- [ ] Rainfall Outlook (shows 2, below normal and above normal)
- [ ] Severe Weather Alert (shows 2)
- [ ] Strong Wind and Large Waves Advisory (shows 2, 25-34kts and 20-25kts)
- [ ] Flash Flood Watch Discontinuation (shows 2

**Comment by AnttiRumpunen** [comment]
Visibility:
- sea area: poor visibility is not visualised
- land area: rain severe is not visualised
- land area: haze saharan extreme is not visualised
- land area: fog severe is not visualised
- sea area Poor visibility is shown in the same category as all land area Visibility warnings

**Comment by AnttiRumpunen** [comment]
Tropical storms
- each category has both land and sea warnings
- discontinuations are not visualised (#22)
- sea: tropical storm warning is not visualised
- land: tropical storm advisory is not visualised
- land: tropical storm watch is not visualised

**Comment by AnttiRumpunen** [comment]
Hurricanes
- discontinuations are not visualised (#22)
- 5 buttons were available, should have been 12 (6 land and 6 sea)
- land: hurricane watch is not visualised
- land: hurricane warning is not visualised
- sea: hurricane advisory is not visualised
- text section: 4 hurricane advisory discontinuations, should be 2 => warnings go in the same as advisories...
- discontinuations have red icon...

**Comment by AnttiRumpunen** [comment]
Wind
- watch and warning go in the same category...

**Comment by AnttiRumpunen** [comment]
Seasonal Temperature
- smartalert + map area yellow, icon orange

Seasonal Rainfall
- below normal is not visualised
- below and above have same generic icon + get into same category

**Comment by AnttiRumpunen** [comment]
Severe weather
- both land and sea warnings go into same category
- land warning is not visualised

**Comment by AnttiRumpunen** [comment]
Strong wind and large wave
- 25-34kts warning is not visualised
- 20-25kts and 25-34kts are both in same category

**Comment by AnttiRumpunen** [comment]
Flash flood
- discontinuations not visualised (#22)
- watch and warning discontinuations go into the same category

**Comment by AnttiRumpunen** [comment]
SmartAlert editor bugs has been reported and hopefully they get fixed soon...

**Comment by AnttiRumpunen** [comment]
All good
